<Project>
  <PropertyGroup>
    <TrackstormVersion>0.1.33</TrackstormVersion>
    <Version>$(TrackstormVersion)</Version>
    <AssemblyVersion>$(TrackstormVersion).0</AssemblyVersion>
    <FileVersion>$(TrackstormVersion).0</FileVersion>
    <InformationalVersion>$(TrackstormVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="TrackstormVersion" Value="$(TrackstormVersion)" />
  </ItemGroup>
</Project>
