using System.Numerics;

namespace Trackstorm.Core.Vehicles;

/// <summary>Inelastic vehicle contact response; raw impact observations remain available to damage authority.</summary>
public static class VehicleCollision
{
    /// <summary>Exchanges equal and opposite momentum once at a contact, without restitution or an upright target.</summary>
    public static (VehiclePhysicsState First, VehiclePhysicsState Second) ResolvePair(
        VehiclePhysicsState first, VehicleConfiguration firstTuning,
        VehiclePhysicsState second, VehicleConfiguration secondTuning, Vector3 normal, Vector3 point)
    {
        if (!VehiclePhysicsState.IsFinite(normal) || Math.Abs(normal.LengthSquared() - 1) > 0.001f || !VehiclePhysicsState.IsFinite(point))
        {
            throw new ArgumentException("Collision requires a unit normal and finite contact point.");
        }
        firstTuning.Validate();
        secondTuning.Validate();
        Vector3 firstLever = point - first.Position;
        Vector3 secondLever = point - second.Position;
        Vector3 relative = first.LinearVelocity + Vector3.Cross(first.AngularVelocity, firstLever) -
            second.LinearVelocity - Vector3.Cross(second.AngularVelocity, secondLever);
        float closing = Math.Max(0, -Vector3.Dot(relative, normal));
        if (closing < 0.000001f) { return (first, second); }
        // Qualification uses relative translation, not yaw generated by the previous solve.
        // Ordinary sustained touching cannot repeatedly manufacture another PIT impulse.
        float approach = Math.Max(0, -Vector3.Dot(first.LinearVelocity - second.LinearVelocity, normal));
        float inverseMass = 1 / firstTuning.Mass + 1 / secondTuning.Mass;
        float maximumImpulse = closing / inverseMass;
        Vector3 firstRotation = RotationPerImpulse(first, firstTuning, firstLever, normal, approach, maximumImpulse);
        Vector3 secondRotation = RotationPerImpulse(second, secondTuning, secondLever, -normal, approach, maximumImpulse);
        float effectiveInverseMass = inverseMass + Vector3.Dot(Vector3.Cross(firstRotation, firstLever) -
            Vector3.Cross(secondRotation, secondLever), normal);
        float impulse = closing / effectiveInverseMass;
        return (Apply(first, firstTuning, normal * impulse, firstRotation * impulse),
            Apply(second, secondTuning, -normal * impulse, secondRotation * impulse));
    }

    /// <summary>Resolves each observed pair once in stable identity order at a common boundary.</summary>
    public static Dictionary<ulong, VehicleObservation> ResolveContacts(
        IReadOnlyDictionary<ulong, VehicleObservation> source, Func<ulong, VehicleConfiguration> configuration)
    {
        var observations = source.ToDictionary(pair => pair.Key, pair => pair.Value);
        var pairs = new HashSet<(ulong, ulong)>();
        foreach (ulong id in observations.Keys.Order())
        {
            foreach (var contact in observations[id].Contacts.Where(c => c.OtherVehicleId != 0).OrderBy(c => Vector3.Dot(c.RelativeVelocity, c.Normal)))
            {
                ulong other = contact.OtherVehicleId;
                if (!observations.ContainsKey(other) || !pairs.Add((Math.Min(id, other), Math.Max(id, other)))) { continue; }
                var first = observations[id]; var second = observations[other];
                var geometry = ContactGeometry(source[id], other);
                var resolved = ResolvePair(first.Physics, configuration(id), second.Physics, configuration(other), geometry.Normal, geometry.Point);
                observations[id] = WithPhysics(first, resolved.First);
                observations[other] = WithPhysics(second, resolved.Second);
            }
        }
        return observations;
    }

    /// <summary>Uses the center of the strongest contact face, so a flat bumper cannot select an arbitrary corner lever.</summary>
    public static (Vector3 Normal, Vector3 Point) ContactGeometry(VehicleObservation observation, ulong otherVehicleId)
    {
        var contacts = observation.Contacts.Where(contact => contact.OtherVehicleId == otherVehicleId)
            .OrderBy(contact => Vector3.Dot(contact.RelativeVelocity, contact.Normal)).ToArray();
        if (contacts.Length == 0) { throw new ArgumentException("A vehicle contact is required."); }
        var strongest = contacts[0];
        float closing = Math.Max(0, -Vector3.Dot(strongest.RelativeVelocity, strongest.Normal));
        var face = contacts.Where(contact => Vector3.Dot(contact.Normal, strongest.Normal) > .95f &&
            Math.Max(0, -Vector3.Dot(contact.RelativeVelocity, contact.Normal)) >= closing * .8f)
            .Select(contact => contact.LocalPosition).Distinct().ToArray();
        Vector3 center = face.Aggregate(Vector3.Zero, (sum, point) => sum + point) / face.Length;
        return (strongest.Normal, observation.Physics.Position + Vector3.Transform(center, observation.Physics.Orientation));
    }

    private static VehicleObservation WithPhysics(VehicleObservation observation, VehiclePhysicsState physics) =>
        new(physics, observation.Support, observation.Contacts, observation.Surface, observation.Wheels, observation.TerrainSupport, observation.WaterDepth);

    private static Vector3 RotationPerImpulse(VehiclePhysicsState body, VehicleConfiguration tuning,
        Vector3 lever, Vector3 normal, float approach, float maximumImpulse)
    {
        Vector3 local = Vector3.Transform(lever, Quaternion.Conjugate(body.Orientation));
        Vector3 direction = Vector3.Transform(normal, Quaternion.Conjugate(body.Orientation));
        Vector3 up = Vector3.Transform(Vector3.UnitY, body.Orientation);
        float rear = Math.Clamp((local.Z / tuning.Wheelbase - 0.05f) / 0.25f, 0, 1);
        float side = Math.Clamp((Math.Abs(direction.X) - 0.35f) / 0.45f, 0, 1);
        float offset = Math.Clamp(Math.Abs(local.X) / (tuning.Wheelbase * 0.25f), 0, 1);
        float speed = (body.LinearVelocity - up * Vector3.Dot(body.LinearVelocity, up)).Length();
        float moving = Math.Clamp((speed - 1) / 5, 0, 1);
        float impact = Math.Clamp((approach - tuning.PitClosingSpeed) / tuning.PitClosingSpeed, 0, 1);
        float qualification = tuning.PitYawResponse <= tuning.CrashRotation || tuning.PitAngularLimit == 0 ? 0 : rear * side * offset * moving * impact;
        Vector3 torque = Vector3.Cross(lever, normal);
        float inertia = 3 / (tuning.Mass * tuning.Wheelbase * tuning.Wheelbase);
        float eccentric = Math.Clamp((Math.Abs(local.Z) / tuning.Wheelbase - 0.08f) / 0.45f, 0, 1) * side * offset * impact;
        if (tuning.VehicleImpactYawResponse <= tuning.CrashRotation || tuning.PitAngularLimit == 0) { eccentric = 0; }
        float extraYaw = Math.Max(Math.Max(0, tuning.VehicleImpactYawResponse - tuning.CrashRotation) * eccentric,
            Math.Max(0, tuning.PitYawResponse - tuning.CrashRotation) * qualification);
        Vector3 response = torque * (tuning.CrashRotation * inertia) + up * (Vector3.Dot(torque, up) * inertia * extraYaw);
        float limit = tuning.CrashAngularLimit + Math.Max(0, tuning.PitAngularLimit - tuning.CrashAngularLimit) * Math.Max(qualification, eccentric);
        // Bound the compliance before computing effective mass. Clipping angular velocity
        // after the solve would leave closing velocity and trigger repeated impulses.
        return limit == 0 ? Vector3.Zero : VehicleMovement.Limit(response, limit / maximumImpulse);
    }

    private static VehiclePhysicsState Apply(VehiclePhysicsState body, VehicleConfiguration tuning, Vector3 impulse, Vector3 rotation) =>
        new(body.Position, body.Orientation, body.LinearVelocity + impulse / tuning.Mass,
            VehicleMovement.Limit(body.AngularVelocity + rotation, tuning.MaximumAngularSpeed));
}
